services:
  # Web Service - Your Flask App
  - type: web
    name: homie-ai-companion
    env: python
    region: oregon
    plan: free
    branch: main
    
    # Build Command - Install dependencies and create database tables
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python create_tables.py
    
    # Start Command - Run the app with Gunicorn
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120
    
    # Health Check
    healthCheckPath: /api/database-health
    
    # Environment Variables
    envVars:
      
      - key: DATABASE_URL
        fromDatabase:
          name: homie-postgres
          property: connectionString
      
      - key: SECRET_KEY
        generateValue: true
      
      - key: GROQ_API_KEY
        sync: false
      
      - key: GOOGLE_API_KEY
        sync: false
      
      - key: FLASK_ENV
        value: production
