services:
  - type: web
    name: homie-ai
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 2"
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: homie-ai-db
          property: connectionString
      # ADD THESE NEW ENVIRONMENT VARIABLES:
      - key: PGHOST
        fromDatabase:
          name: homie-ai-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: homie-ai-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: homie-ai-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: homie-ai-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: homie-ai-db
          property: password

databases:
  - name: homie-ai-db
    databaseName: homie_ai_db
    user: homie_ai_user
    plan: free
